### PR TITLE
Fix error messages being duplicated

### LINKED ISSUE #4: Error messages are duplicated
## Description

When parsing a query fails with an error, on converting the resulting error object to a string, the string contains two copies of the error message.

## Environment

1. OS (where TypeDB server runs): Mac OS 11
2. TypeDB version (and platform): TypeDB 2.2
3. TypeDB client: client-nodejs

## Reproducible Steps

Run the following query: `match $x sb thing;` and observe the error message returned

## Expected Output

```
[GQL03] TypeQL Error: There is a syntax error at line 1:
match $x sb thing;
         ^
no viable alternative at input 'match $x sb'
```

## Actual Output

```
[GQL03] TypeQL Error: There is a syntax error at line 1:
match $x sb thing;
         ^
no viable alternative at input 'match $x sb'
[GQL03] TypeQL Error: There is a syntax error at line 1:
match $x sb thing;
         ^
no viable alternative at input 'match $x sb'
```

### LINKED ISSUE #222: Error messages are duplicated
## Description

When parsing a query fails with an error, on converting the resulting error object to a string, the string contains two copies of the error message.

## Environment

1. OS (where TypeDB server runs): Mac OS 11
2. TypeDB version (and platform): TypeDB 2.2
3. TypeDB client: client-nodejs

## Reproducible Steps

Run the following query: `match $x sb thing;` and observe the error message returned

## Expected Output

```
[GQL03] TypeQL Error: There is a syntax error at line 1:
match $x sb thing;
         ^
no viable alternative at input 'match $x sb'
```

## Actual Output

```
[GQL03] TypeQL Error: There is a syntax error at line 1:
match $x sb thing;
         ^
no viable alternative at input 'match $x sb'
[GQL03] TypeQL Error: There is a syntax error at line 1:
match $x sb thing;
         ^
no viable alternative at input 'match $x sb'
```

### PR DESCRIPTION
**Pull request by alexjpwalker**
## What is the goal of this PR?

Previously, when parsing a query failed with an error, on converting the resulting error object to a string, the string would contain two copies of the error message - e.g:
```
[GQL03] TypeQL Error: There is a syntax error at line 1:
match $x sb thing;
         ^
no viable alternative at input 'match $x sb'
[GQL03] TypeQL Error: There is a syntax error at line 1:
match $x sb thing;
         ^
no viable alternative at input 'match $x sb'
```
This is now fixed and error messages are no longer duplicated. (Also, the error code is now TQL)

## What are the changes implemented in this PR?

- Fix error messages being duplicated (fixes vaticle/typeql#222)
- Change error code from GQL to TQL

### CODE REVIEW

File: parser/Parser.java [hunk 1]
```diff
@@ -136,6 +136,7 @@
             // DefaultErrorStrategy + LL_EXACT_AMBIG_DETECTION
             // This was not set to default parsing strategy, but it is useful
             // to produce detailed/useful error message
+            errorListener.clearErrors();
```
Comment (alexjpwalker) [inline parser/Parser.java:139]: The error handling logic is as follows:
1. Attach error listener to parser - whenever a parser error is thrown, it gets stored in the Listener
2. Parse query with optimised parser (returns less useful error messages)
3. If parsing fails, re-parse query with strict parser (returns more detailed error messages)
4. If parsing fails (which it will), dump all errors in the Listener to an exception string.

Trouble is, this flow causes 2 errors (which may not necessarily be identical, but often are) to be piped into the Listener, and they both make it into the output.

To fix this issue, we clean the first (less precise) error from the Listener before storing the second, more precise one.

**Review by alexjpwalker — COMMENTED** [review]
These changes look good

**Review by haikalpribadi — APPROVED** [review]
